name: CD - Development
on:
push:
branches: [ develop ]
jobs:
cd-dev:
runs-on: ubuntu-latest
environment: development
steps:
- name: Checkout
uses: actions/checkout@v4
- name: Deploy to Render (Development)
run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_DEV_URL }}
- name: Confirm Deployment
run: echo "Deployed to Development at $(date)"